### ISSUE TITLE
className in ListItemProps overrides listItemClass

### ISSUE THREAD

**Issue by Bopzor** [VagnerNico/mui-swipeable-list-item#1]
Hi!

Thanks for this nice and simple to use swipeable version of MUI `ListItem`.  

I noticed that, when passing `className` to `ListItemProps`, it overrides the `mui-swipeable-list-item` styles of the `ListItem` instead of merging them. 

This cause the `background-color` and the `transform` properties to no longer been set.  
You can check this working (in chrome, responsive mode) example: [CodeSandbox Reproduction](https://ymo77.csb.app/)

I think it can be simply fixed using `clsx`-like lib to merged received `className` prop and the `listItemClass` one. 

If you think it's relevant, I can make a PR.
> if there is any crontributing guides lines, don't hesitate to share them with me :)

**Comment by VagnerNico** [comment]
Hi, thanks for the feedback.
I'm really sorry to answer so late, months after issuing the problem.
With all this pandemic situation, I'd got too much work and forgot this lib.
Looking forward to receiving your PR, I promise that I review it as soon as committed.
